DjangoProjects/urls.py
from django.contrib import admin
from django.urls import path
# from restaurants.views import hello
# from restaurants.views import welcome
# from restaurants.views import contact
# from restaurants.views import AboutView
# from restaurants.views import HelloTemplateView
# from restaurants.views import WelcomeTemplateView
# from restaurants.views import ContactTemplateView
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.urls import include

from restaurants.views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
)
from userauth.views import SignUpView, UserProfileView, UserLoginView, UserProfileUpdateView


from restaurants.views import RestaurantListView, RestaurantDetailView,restaurant_createview,RestaurantCreateView
from userauth.views import UserLoginView,SignUpView,UserProfileView,UserProfileUpdateView
from django.contrib.auth.views import LogoutView
# from restaurants.views import restaurant_list


# urlpatterns = [
    # path('admin/', admin.site.urls),
    # path ('home/',TemplateView.as_view(template_name="hello.html")),
    # path ('about/',TemplateView.as_view(template_name="about.html")),
    # path ('restaurant/',RestaurantListView.as_view()),
    # # path('restaurant/<str:slug>',RestaurantListView.as_view()),
    # path('restaurant/<int:rest_id>/',RestaurantDetailView.as_view()),
    # path('restaurant/<str:slug>',RestaurantDetailView.as_view()),
    # # path('restaurant/create/',restaurant_createview),
    # path('restaurant/create/',RestaurantCreateView.as_view()),
    # path('login/',CustomLoginView.as_view()),
    # path('logout/',LogoutView.as_view(next_page='/login/')),
    # path('signup/',SignUpView.as_view()),
    # path('user-profile/',UserProfileView.as_view()),
    # path('user-profile/update/',UserProfileUpdateView.as_view()),
    # ]
    # path('home/', hello), #home page open by calling function or html file hello
    # path('welcome/', welcome),
    # path('contact/', contact),
    # path('about/', AboutView.as_view()),
    # class call garna .as_view() add garnaparcha
#     path('home/', HelloTemplateView.as_view()),
#     path('welcome/', WelcomeTemplateView.as_view()),
#     path('contact/', ContactTemplateView.as_view()),
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("userauth.urls", namespace="userauth")),
    path('restaurant/', include("restaurants.urls", namespace="restaurants")),
    path('home/', TemplateView.as_view(template_name="hello.html"), name="home"),
    path('about/', TemplateView.as_view(template_name="about.html"), name="about"),
    path('items/', include("fooditem.urls", namespace="fooditem")),
]

fooditem/urls.py
from django.urls import path
from .views import FoodItemListView, FoodItemDetailView,FoodItemCreateView,FoodItemUpdateView

app_name = 'fooditem'

urlpatterns = [
    path('',FoodItemListView.as_view(),name="list"),
    path('create/', FoodItemCreateView.as_view(), name="create"),
    path('<str:pk>/',FoodItemDetailView.as_view(),name="detail"),
    path('<str:pk>/update/',FoodItemUpdateView.as_view(), name="update"),
]

userauth/urls.py
from django.contrib import admin
from django.urls import path
# from restaurants.views import hello
# from restaurants.views import welcome
# from restaurants.views import contact
# from restaurants.views import AboutView
# from restaurants.views import HelloTemplateView
# from restaurants.views import WelcomeTemplateView
# from restaurants.views import ContactTemplateView
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from restaurants.views import RestaurantListView, RestaurantDetailView,restaurant_createview,RestaurantCreateView
from userauth.views import UserLoginView,SignUpView,UserProfileView,UserProfileUpdateView
from django.contrib.auth.views import LogoutView
# from restaurants.views import restaurant_list

from django.urls import path
from django.contrib.auth.views import LogoutView

from userauth.views import SignUpView, UserProfileView, UserLoginView, UserProfileUpdateView
app_name= "userauth"
urlpatterns = [
    path('login/', UserLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page="/login/"), name="logout"),
    path('signup/', SignUpView.as_view(), name="signup"),
    path('user-profile/', UserProfileView.as_view(), name="profile"),
    path('user-profile/update/', UserProfileUpdateView.as_view(), name="update"),
]

templates/snippets/css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

templates/snippets/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'restaurants:list' %}">Restaurants</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="#">DjangoProjects</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userauth:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
</nav>